### ISSUE TITLE
MySQL error with Classifieds website

### ISSUE THREAD

**Issue by vardaan123** [web-arena-x/visualwebarena#31]
Hi, I am trying to setup the classifieds website as outlined here https://github.com/web-arena-x/visualwebarena/blob/main/environment_docker/README.md#classifieds-website

When I execute `docker exec classifieds_db mysql -u root -ppassword osclass -e 'source docker-entrypoint-initdb.d/osclass_craigslist.sql'  # Populate DB with content`, I get the error `ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2).`

Since docker is not affected by my local environment, it should run ideally. Kindly help me resolve this.

My `docker_compose.yml` is given below
```
version: '3.1'
  
services:
  web:
    image: jykoh/classifieds:latest
    ports:
      - "9980:9980"
    depends_on:
      - db
    container_name: classifieds
    environment:
      - CLASSIFIEDS=http://127.0.0.1:9980/
      - RESET_TOKEN=4b61655535e7ed388f0d40a93600254c
  db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: osclass
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    container_name: classifieds_db

volumes:
  db_data: {}
```
